name: Dockerimage Blender 2.79

on:
  push:
    branches: 
      - bl_2.79

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.0.0
      with:
        branch: bl_2.79
    - name: Build the Docker image
      env:
        HUB_NAME: ${{ secrets.DOCKER_NAME }}
        HUB_KEY: ${{ secrets.DOCKER_TOKEN }}
      run: |  
        docker login -u $HUB_NAME -p $HUB_KEY
        docker build . --file Dockerfile --tag zocker160/blender-crowdrender:bl_2.79
        docker push zocker160/blender-crowdrender
