name: Dockerimage latest

on:
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.0.0
      with:
        branch: master
    - name: Build the Docker image
      env:
        HUB_NAME: ${{ secrets.DOCKER_NAME }}
        HUB_KEY: ${{ secrets.DOCKER_TOKEN }}
      run: |  
        docker login -u $HUB_NAME -p $HUB_KEY
        docker build . --file Dockerfile --tag zocker160/blender-crowdrender:latest
        docker tag zocker160/blender-crowdrender:latest zocker160/blender-crowdrender:bl_2.81
        docker push zocker160/blender-crowdrender

#    - name: Add Readme to DockerHub
#      uses: peter-evans/dockerhub-description@v2.1.0
#      env:
#        DOCKERHUB_USERNAME: ${{ secrets.DOCKER_NAME }}
#        DOCKERHUB_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
#        DOCKERHUB_REPOSITORY: zocker160/blender-crowdrender
#        README_FILEPATH: ./README.md
